ToanThangEdu/ToanThangEdu/Models/DocumentItem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToanThangEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentItem
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string DocumentContent { get; set; }
        public string DocumentURL { get; set; }
        public Nullable<long> CategoryId { get; set; }
    
        public virtual DocumentsCategory DocumentsCategory { get; set; }
    }
}

ToanThangEdu/ToanThangEdu/Areas/Admin/Controllers/DocumentItemsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using ToanThangEdu.Models;

namespace ToanThangEdu.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, Teacher")]
    public class DocumentItemsController : Controller
    {
        private ToanThangEducationDBEntities db = new ToanThangEducationDBEntities();

        // GET: Admin/DocumentItems
        public ActionResult Index(int? page)
        {
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            var documentItems = db.DocumentItems.Include(d => d.DocumentsCategory).ToList();
            return View(documentItems.ToPagedList(pageNumber, pageSize));
        }       
        public FileResult PDFDisplay(int? id)
        {            
            var document = db.DocumentItems.Find(id);
            string filepath = Server.MapPath("~/images/Document/"+ document.DocumentURL);            
            return File(filepath, "application/pdf",document.DocumentURL);
        }

        public FileResult DisplayPDF(long? id)
        {
            DocumentItem documentItem = db.DocumentItems.Find(id);
            return File("~/images/Document/" + documentItem.DocumentURL, "application/pdf");
        }
        // GET: Admin/DocumentItems/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentItem documentItem = db.DocumentItems.Find(id);
            if (documentItem == null)
            {
                return HttpNotFound();
            }
            return View(documentItem);
        }

        // GET: Admin/DocumentItems/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.DocumentsCategories, "Id", "Name");
            return View();
        }

        // POST: Admin/DocumentItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,DocumentContent,DocumentURL,CategoryId")] DocumentItem documentItem, HttpPostedFileBase fileUpload)
        {
            Regex imageFilenameRegex = new Regex(@"(.*?)\.(pdf|doc|docx|rar)$");
            //Regex imageFilenameRegex = new Regex(@"(.*?)\.(pdf)$");
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chưa có file đính kèm";
                ViewBag.CategoryId = new SelectList(db.DocumentsCategories, "Id", "Name", documentItem.CategoryId);
                return View();
            }
            if (!imageFilenameRegex.IsMatch(fileUpload.FileName.ToLower()))
            {
                //ViewBag.ThongBao = "File tải lên phải có định dạng pdf.";
                ViewBag.ThongBao = "File tải lên phải có định dạng pdf,doc hoặc docx.";
                ViewBag.CategoryId = new SelectList(db.DocumentsCategories, "Id", "Name", documentItem.CategoryId);
                return View();
            }
            if (fileUpload.ContentLength > 0)
            {
                var fileName = Path.GetFileName(fileUpload.FileName.ToLower());
                if (fileName != null)
                {
                    DateTime currentDate = DateTime.Now;
                    var currentDateTick = currentDate.Ticks;             
                    var path = Path.Combine(Server.MapPath("~/images/Document"), currentDateTick + "_" + fileName);                    
                    fileUpload.SaveAs(path);
                    documentItem.DocumentURL = currentDateTick + "_" + fileName;
                }
                
            }
            if (ModelState.IsValid)
            {
                db.DocumentItems.Add(documentItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.DocumentsCategories, "Id", "Name", documentItem.CategoryId);
            return View(documentItem);
        }

        // GET: Admin/DocumentItems/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentItem documentItem = db.DocumentItems.Find(id);
            Session["document"] = documentItem;
            if (documentItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.DocumentsCategories, "Id", "Name", documentItem.CategoryId);
            return View(documentItem);
        }

        // POST: Admin/DocumentItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long? Id, string Name, long? CategoryId, string DocumentContent, HttpPostedFileBase fileUpload)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DocumentItem documentItem = db.DocumentItems.Find(Id);

            //Regex imageFilenameRegex = new Regex(@"(.*?)\.(pdf)$");
            Regex imageFilenameRegex = new Regex(@"(.*?)\.(pdf|doc|docx)$");
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chưa có file đính kèm";
                ViewBag.CategoryId = new SelectList(db.DocumentsCategories, "Id", "Name", documentItem.CategoryId);
                return View();
            }
            if (!imageFilenameRegex.IsMatch(fileUpload.FileName.ToLower()))
            {
                //ViewBag.ThongBao = "File tải lên phải có định dạng pdf.";
                ViewBag.ThongBao = "File tải lên phải có định dạng pdf, doc hoặc docx.";
                ViewBag.CategoryId = new SelectList(db.DocumentsCategories, "Id", "Name", documentItem.CategoryId);
                return View();
            }
            if (fileUpload.ContentLength > 0)
            {
                var fileName = Path.GetFileName(fileUpload.FileName.ToLower());
                if (fileName != null)
                {
                    DateTime currentDate = DateTime.Now;
                    var currentDateTick = currentDate.Ticks;
                    var path = Path.Combine(Server.MapPath("~/images/Document"), currentDateTick + "_" + fileName);
                    fileUpload.SaveAs(path);
                    documentItem.DocumentURL = currentDateTick + "_" + fileName;
                }
                
            }
            if (Name != null && DocumentContent != null)
            {
                documentItem.Name = Name;
                documentItem.DocumentContent = DocumentContent;
                documentItem.CategoryId = CategoryId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Session["document"] = null;
            ViewBag.CategoryId = new SelectList(db.DocumentsCategories, "Id", "Name", documentItem.CategoryId);
            return View(documentItem);
        }

        // GET: Admin/DocumentItems/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentItem documentItem = db.DocumentItems.Find(id);
            if (documentItem == null)
            {
                return HttpNotFound();
            }
            return View(documentItem);
        }

        // POST: Admin/DocumentItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            DocumentItem documentItem = db.DocumentItems.Find(id);
            db.DocumentItems.Remove(documentItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/DocumentItems/Create.cshtml
@model ToanThangEdu.Models.DocumentItem

@{
    ViewBag.Title = "TẠO TÀI LIỆU THAM KHẢO";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}




@using (Html.BeginForm("Create", "DocumentItems", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container form-horizontal">
        <div class="row">
            <div class="col-lg-10">
                <div class="widget-item">
                    <div class="form-horizontal">
                        <h4 class="text-center">TẠO TÀI LIỆU THAM KHẢO</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.Label("Chọn thể loại:", "Chọn thể loại:", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("File đính kèm:", new { @class = "control-label col-lg-3" })
                            <div class="col-lg-8">
                                <input type="file" name="fileUpload" class="btn btn-default form-control" />
                                <h5 style="color:red">@ViewBag.ThongBao</h5>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Tiêu đề: ", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Nội dung sơ lược:", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.EditorFor(model => model.DocumentContent, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DocumentContent, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-8">
                                <input type="submit" class="btn btn-primary" value="Submit" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/DocumentItems/Delete.cshtml
@model ToanThangEdu.Models.DocumentItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="container form-horizontal">
    <div class="row">

        <div class="col-lg-10">
            <div class="widget-item">


                <div class="form-horizontal">
                    <h4 class="text-center">XÓA TÀI LIỆU</h4>
                    <hr />
                    <h3>Bạn có muốn xóa tài liệu này?</h3>
                    <div>                        
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.DocumentContent)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.DocumentContent)
                            </dd>

                            <dt>

                            </dt>

                            <dd>
                                @{
                                    var str = Model.DocumentURL;
                                    if (str.Contains(".pdf"))
                                    {
                                        <iframe src="@Url.Action("DisplayPDF", "DocumentItems",new {id = Model.Id })" width="100%" height="700" frameborder="0"></iframe>
                                    }
                                    else
                                    {
                                        <iframe src="https://docs.google.com/gview?embedded=true&url=http://www.daythemdanang.edu.vn/images/Document/@str" width="100%" height="700" frameborder="0"></iframe>
                                    }

                            <!-- /.blog-post-meta -->}
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.DocumentsCategory.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.DocumentsCategory.Name)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/DocumentItems/Edit.cshtml
@model ToanThangEdu.Models.DocumentItem

@{
    ViewBag.Title = "CHỈNH SỬA TÀI LIỆU";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Edit", "DocumentItems", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container form-horizontal">
        <div class="row">
            <div class="col-lg-10">
                <div class="widget-item">
                    <div class="form-horizontal">
                        <h4 class="text-center">CHỈNH SỬA TÀI LIỆU</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, "Tên tài liệu", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.CategoryId, "Thể loại", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Nội dung sơ lược: ", "Nội dung sơ lược", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.EditorFor(model => model.DocumentContent, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DocumentContent, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                            @Html.Label("Nội dung file", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.EditorFor(model => model.DocumentURL, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DocumentURL, "", new { @class = "text-danger" })
                                <iframe src="https://docs.google.com/gview?url=http://www.tutorialspoint.com/cprogramming/cprogramming_tutorial.pdf&embedded=true" style="width:600px; height:500px;" frameborder="0"></iframe>
                            </div>
                        </div>*@
                
                        <div class="form-group">
                            @Html.Label("File đính kèm:", new { @class = "control-label col-lg-3" })
                            <div class="col-lg-8">
                                <input type="file" name="fileUpload" class="btn btn-default form-control" />
                                <h5 style="color:red">@ViewBag.ThongBao</h5>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-3 col-lg-9">
                                @Html.ActionLink("Xem nội dung file", "DisplayPDF", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                                <input type="submit" value="Lưu thay đổi" class="btn btn-primary" />
                                @Html.ActionLink("Quay lại", "Index", "DocumentItems", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/DocumentItems/Index.cshtml
@model IEnumerable<ToanThangEdu.Models.DocumentItem>

@{
    ViewBag.Title = "QUẢN LÝ CHIA SẺ TÀI LIỆU";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container form-horizontal">
    <div class="row">
        <div class="col-lg-12">
            <div class="widget-item">
                <div class="form-horizontal">
                    <h4 class="text-center">TÀI LIỆU THAM KHẢO</h4>
                    <hr />
                    <p>
                        @Html.ActionLink("Thêm chia sẻ", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayName("Tên tài liệu")
                            </th>
                            <th>
                                @Html.DisplayName("Nội dung sơ lược")
                            </th>
                            <th>
                                @Html.DisplayName("Thể loại")
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DocumentContent)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DocumentsCategory.Name)
                                </td>
                                <td>
                                    <a class='btn btn-warning btn-sm' href="@Url.Action("Edit", "DocumentItems", new { id = item.Id })" role='button'><span title="Chỉnh sửa" class='glyphicon glyphicon-pencil' aria-hidden='true'></span></a>
                                    <a class='btn btn-warning btn-sm' href="@Url.Action("DisplayPDF", "DocumentItems", new { id = item.Id })" role='button'><span title="Xem trước" class='glyphicon glyphicon-book' aria-hidden='true'></span></a>
                                    <a class='btn btn-danger btn-sm' href="@Url.Action("Delete", "DocumentItems", new { id = item.Id })" role='button'><span title="Xóa" class='glyphicon glyphicon-trash' aria-hidden='true'></span></a>

                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>