ToanThangEdu/ToanThangEdu/Areas/Admin/Controllers/ConfirmAccountController.cs
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ToanThangEdu.Models;

namespace ToanThangEdu.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ConfirmAccountController : Controller
    {
        private ToanThangEducationDBEntities db = new ToanThangEducationDBEntities();
        public ConfirmAccountController()
        {
        }

        public ConfirmAccountController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public ActionResult Index(int? page)
        {
            var users = db.AspNetUsers.OrderByDescending(x => x.UserName).Where(x => x.Activated != true && x.Id != "9c8297f6-6207-4f50-82d9-75cbbab46695");
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(users.ToList().ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Confirm(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = db.AspNetUsers.Where(x => x.Id == id).FirstOrDefault();
            user.Activated = true;
            db.SaveChanges();
            return RedirectToAction("Index", "Admin/ConfirmAccount");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                if (user.UserName == User.Identity.Name)
                {
                    Response.Redirect("/Admin/ConfirmAccount");
                    return null;
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index","Admin/ConfirmAccount");
            }
            return View();
        }
    }
}

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/ConfirmAccount/Index.cshtml
@model PagedList.IPagedList<ToanThangEdu.Models.AspNetUser>
@using PagedList.Mvc;
@{
    ViewBag.Title = "QUẢN LÝ XÁC NHẬN TÀI KHOẢN";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4 class="text-center">QUẢN LÝ XÁC NHẬN TÀI KHOẢN</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Tên đăng nhập")
        </th>
        <th>
            @Html.DisplayName("Email")
        </th>
        @*<th>
                @Html.DisplayName("Xác nhận")
            </th>*@
        <th>

        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.HomeTown)
                </td>*@
            <td>
                <div class="row">
                    <div class="col-lg-2">
                        @using (Html.BeginForm("Confirm", "ConfirmAccount", new { area = "" }, FormMethod.Post, new { id = item.Id }))
                        {
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@item.Id" />
                            <a class='btn btn-warning btn-sm' href="javascript:document.getElementById('@item.Id').submit()" role='button'><span title="Xác nhận" class='glyphicon glyphicon-ok' aria-hidden='true'></span></a>

                        }
                    </div>
                    <div class="col-lg-2">
                        @using (Html.BeginForm("Delete", "ConfirmAccount", new { area = "" }, FormMethod.Post, new { id = "delete_" +@item.Id }))
                        {
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@item.Id" />
                            <a class='btn btn-danger btn-sm' href="javascript:document.getElementById('delete_@item.Id').submit()" role='button'><span title="Xóa" class='glyphicon glyphicon-trash' aria-hidden='true'></span></a>
                        }
                    </div>
                    
                </div>
                
            </td>
        </tr>
        
    }
</table>

@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))