ToanThangEdu/ToanThangEdu/Models/DocumentsCategory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToanThangEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentsCategory()
        {
            this.DocumentItems = new HashSet<DocumentItem>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RootId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentItem> DocumentItems { get; set; }
    }
}

ToanThangEdu/ToanThangEdu/Areas/Admin/Controllers/DocumentsCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToanThangEdu.Models;

namespace ToanThangEdu.Areas.Admin.Controllers
{
    public class Menu
    {
        public Int64 Id;
        public string PaMenu;
        public string ChiMenu;
    }

    public class MenuChild
    {
        public Int64 Id;
        public string ChiMenu;
    }

    public class MenuInView
    {
        public Int64 Id;
        public string PaMenu;
        public List<MenuChild> ChiMenu;
    }
    [Authorize(Roles = "Admin")]
    public class DocumentsCategoriesController : Controller
    {
        private ToanThangEducationDBEntities db = new ToanThangEducationDBEntities();

        public List<Menu> GetListRoot()
        {
            var listRoot = new List<Menu>();
            foreach (var item in db.DocumentsCategories.OrderBy(x=>x.Id))
            {
                if (item.RootId == 0)
                {
                    Menu tmp = new Menu();
                    tmp.Id = item.Id;
                    tmp.PaMenu = item.Name;
                    listRoot.Add(tmp);
                }
            }
            Menu temp = new Menu();
            temp.Id = 0;
            temp.PaMenu = "Thể loại gốc";
            listRoot.Add(temp);
            return listRoot;
        }
        // GET: Admin/DocumentsCategories
        public ActionResult Index()
        {
            var listMenu = new List<Menu>();
            foreach (var item in db.DocumentsCategories.OrderBy(x=>x.Id))
            {
                var menuTmp = new Menu();
                menuTmp.Id = item.Id;
                if (item.RootId != 0)
                {
                    var tmp = (DocumentsCategory)db.DocumentsCategories.Where(x => x.Id == item.RootId).FirstOrDefault();
                    if (tmp == null)
                    {
                        menuTmp.PaMenu = "Thể loại gốc đã được xóa";
                    }
                    else
                    {
                        menuTmp.PaMenu = tmp.Name;
                    }                       
                    
                }
                else
                {
                    menuTmp.PaMenu = item.Name;
                }
                
                menuTmp.ChiMenu = item.Name;
                listMenu.Add(menuTmp);
            }
            ViewBag.Menu = listMenu;
            return View();
        }

        // GET: Admin/DocumentsCategories/Create
        public ActionResult Create()
        {
            ViewBag.RootList = GetListRoot();
            return View();
        }

        // POST: Admin/DocumentsCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Name, int rootId)
        {
            if (Name != null)
            {
                DocumentsCategory documentsCategory = new DocumentsCategory();
                documentsCategory.Name = Name;
                documentsCategory.RootId = rootId;

                db.DocumentsCategories.Add(documentsCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View();
        }

        // GET: Admin/DocumentsCategories/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentsCategory documentsCategory = db.DocumentsCategories.Find(id);
            if (documentsCategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.RootList = GetListRoot();
            return View(documentsCategory);
        }

        // POST: Admin/DocumentsCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int Id, int rootId , string Name)
        {
            if (Name != null)
            {
                var tmp = db.DocumentsCategories.Where(x => x.Id == Id).FirstOrDefault();
                tmp.Name = Name;
                tmp.RootId = rootId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RootList = GetListRoot();
            return View();
        }

        // GET: Admin/DocumentsCategories/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentsCategory documentsCategory = db.DocumentsCategories.Find(id);
            if (documentsCategory == null)
            {
                return HttpNotFound();
            }
            return View(documentsCategory);
        }

        // POST: Admin/DocumentsCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            DocumentsCategory documentsCategory = db.DocumentsCategories.Find(id);
            db.DocumentsCategories.Remove(documentsCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/DocumentsCategories/Create.cshtml
@model ToanThangEdu.Models.DocumentsCategory
@using ToanThangEdu.Areas.Admin.Controllers
@{
    ViewBag.Title = "TẠO THỂ LOẠI TÀI LIỆU";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    List<SelectListItem> listRoot = new List<SelectListItem>();
    foreach (var item in (List<Menu>)ViewBag.RootList)
    {
        listRoot.Add(new SelectListItem
        {
            Text = item.PaMenu,
            Value = item.Id.ToString(),
        });
    }
}


@using (Html.BeginForm("Create", "DocumentsCategories", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container form-horizontal">
        <div class="row">
            <div class="col-lg-10">
                <div class="widget-item">


                    <div class="form-horizontal">
                        <h4 class="text-center">TẠO THỂ LOẠI TÀI LIỆU</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.Label("Root: ", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-4">
                                @Html.DropDownList("RootId", listRoot, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Tên: ", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-8">
                                <input type="text" class="form-control" name="Name" placeholder="" required aria-describedby="basic-addon1">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-lg-9">
                                <input type="submit" class="btn btn-primary" value="Submit" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/DocumentsCategories/Delete.cshtml
@model ToanThangEdu.Models.DocumentsCategory

@{
    ViewBag.Title = "XÓA THỂ LOẠI TÀI LIỆU";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container form-horizontal">
    <div class="row">
        <div  class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="widget-item">
                <div class="form-horizontal">
                    <h4 class="text-center">XÓA THỂ LOẠI TÀI LIỆU</h4>
                    
                    <hr />
                    <h3>Bạn có muốn xóa thể loại này?</h3>
                    <div>                        
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayName("Tên: ")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-group">
                                <div class="col-md-offset-2 col-lg-10">
                                    <input type="submit" value="Xóa" class="btn btn-danger" />
                                    @Html.ActionLink("Quay lại", "Index", "DocumentsCategories", null, new { @class = "btn btn-primary" })
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/DocumentsCategories/Edit.cshtml
@model ToanThangEdu.Models.DocumentsCategory
@using ToanThangEdu.Areas.Admin.Controllers
@{
    ViewBag.Title = "CHỈNH SỬA THỂ LOẠI TÀI LIỆU";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<SelectListItem> listRoot = new List<SelectListItem>();
    foreach (var item in (List<Menu>)ViewBag.RootList)
    {
        listRoot.Add(new SelectListItem
        {
            Text = item.PaMenu,
            Value = item.Id.ToString(),
        });
    }

}

@using (Html.BeginForm("Edit", "DocumentsCategories", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container form-horizontal">
        <div class="row">
            <div class="col-lg-10">
                <div class="widget-item">
                    <div class="form-horizontal">
                        <h4 class="text-center">CHỈNH SỬA THỂ LOẠI TÀI LIỆU</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.Label("Thể loại gốc: ", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-4">
                                @Html.DropDownList("RootId", listRoot, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Tên: ", htmlAttributes: new { @class = "control-label col-lg-3" })
                            <div class="col-lg-8">
                                <input type="text" class="form-control" name="Name" value="@Model.Name" required aria-describedby="basic-addon1">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-lg-10">
                                <input type="submit" value="Lưu thay đổi" class="btn btn-primary" />
                                @Html.ActionLink("Quay lại", "Index", "DocumentsCategories", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

ToanThangEdu/ToanThangEdu/Areas/Admin/Views/DocumentsCategories/Index.cshtml
@model IEnumerable<ToanThangEdu.Models.DocumentsCategory>
@using ToanThangEdu.Areas.Admin.Controllers
@{
    ViewBag.Title = "QUẢN LÝ THỂ LOẠI CHIA SẺ TÀI LIỆU";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container form-horizontal">
    <div class="row">
        <div class="col-lg-10">
            <div class="widget-item">
                <div class="form-horizontal">
                    <h4 class="text-center">THỂ LOẠI TÀI LIỆU</h4>
                    <hr />
                    <p>
                        @Html.ActionLink("Thêm loại mới", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayName("Thể loại gốc")
                            </th>
                            <th>
                                @Html.DisplayName("Tên")
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in (List<Menu>)ViewBag.Menu)
                        {
                            <tr>
                                <td>
                                    @item.PaMenu
                                </td>
                                <td>
                                    @item.ChiMenu
                                </td>
                                <td>
                                    <a class='btn btn-warning btn-sm' href="@Url.Action("Edit", "DocumentsCategories", new { id = item.Id })" role='button'><span title="Chỉnh sửa" class='glyphicon glyphicon-pencil' aria-hidden='true'></span></a>
                                    <a class='btn btn-danger btn-sm' href="@Url.Action("Delete", "DocumentsCategories", new {id = item.Id })" role='button'><span title="Xóa" class='glyphicon glyphicon-trash' aria-hidden='true'></span></a>

                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>