ToanThangEdu/ToanThangEdu/Controllers/UserDocumentItemsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToanThangEdu.Models;

namespace ToanThangEdu.Controllers
{
    [Authorize(Roles = "Student, Admin, Teacher")]
    public class UserDocumentItemsController : Controller
    {
        private ToanThangEducationDBEntities db = new ToanThangEducationDBEntities();

        // GET: UserDocumentItems
        [AllowAnonymous]
        public ActionResult Index(int? page,int? id)
        {
            ViewData["item"] = db.DocumentsCategories.ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);            
            if (id != null)
            {
                var documentItems1 = db.DocumentItems.Include(d => d.DocumentsCategory).Where(x=>x.CategoryId==id).ToList();
                ViewBag.Title = db.DocumentsCategories.Where(x=>x.Id==id).Select(xy=>xy.Name).FirstOrDefault().ToString() + " - Thể loại tài liệu ";
                return View(documentItems1.ToPagedList(pageNumber, pageSize));
            }
            var documentItems = db.DocumentItems.Include(d => d.DocumentsCategory).ToList();
            ViewBag.Title = "Tài Liệu - Trung tâm Toàn Thắng";
            return View(documentItems.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult GetPdf(string fileName)
        {
            var fileStream = new FileStream("~/images/Document/" + fileName,
                                             FileMode.Open,
                                             FileAccess.Read
                                           );
            var fsResult = new FileStreamResult(fileStream, "application/pdf");
            return fsResult;
        }

        [AllowAnonymous]
        public FileResult DisplayPDF(long? id)
        {
            DocumentItem documentItem = db.DocumentItems.Find(id);
            return File("~/images/Document/"+documentItem.DocumentURL, "application/pdf");
        }

        // GET: UserDocumentItems/Details/5
        public FileResult Download(long? id)
        {
            var document = db.DocumentItems.Find(id);
            string filepath = Server.MapPath("~/images/Document/" + document.DocumentURL);
            return File(filepath, "application/pdf", document.DocumentURL);
        }

        [AllowAnonymous]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentItem documentItem = db.DocumentItems.Find(id);
            ViewData["item"] = db.DocumentsCategories.ToList();            
            if (documentItem == null)
            {
                return HttpNotFound();
            }
            return View(documentItem);
        }

        // GET: UserDocumentItems/Create
       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToanThangEdu/ToanThangEdu/Views/UserDocumentItems/Details.cshtml
@model ToanThangEdu.Models.DocumentItem
@using ToanThangEdu.Models;
@{
    var list = (List<DocumentsCategory>)ViewData["item"];
    ViewBag.Title = "Tài Liệu - " + Model.Name;
    Layout = "~/Views/Shared/_ToanThangLayout.cshtml";
}
<div class="container">
    <div class="page-title clearfix">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center page-active">
                    <h1><span class="page-active">@Html.DisplayFor(model => model.DocumentsCategory.Name)</span></h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">

        <!-- Here begin Main Content -->
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <div class="blog-post-container">
                        <div class="blog-post-image">
                            @{
                                var str = Model.DocumentURL;
                                if (str.EndsWith(".pdf"))
                                {
                                    <iframe src="@Url.Action("DisplayPDF", "UserDocumentItems",new {id = Model.Id })" width="100%" height="700" frameborder="0"></iframe>
                                }
                                else
                                {
                                    <iframe src="https://docs.google.com/gview?embedded=true&url=http://www.daythemdanang.edu.vn/images/Document/@str" width="100%" height="700" frameborder="0"></iframe>
                                }

                            <!-- /.blog-post-meta -->}
                        </div> <!-- /.blog-post-image -->

                        <div class="blog-post-inner">
                            <h3 class="blog-post-title">@Html.DisplayFor(model => model.Name)</h3>
                            <p>
                                <blockquote>@Html.Raw(Model.DocumentContent)</blockquote>
                            </p>
                            <p>@Html.ActionLink("Tải xuống", "Download", new { id = Model.Id }, new { target = "_blank", @class = "btn btn-success" })</p>
                        </div>
                    </div> <!-- /.blog-post-container -->
                </div> <!-- /.col-md-12 -->
            </div> <!-- /.row -->

        </div> <!-- /.col-md-8 -->
        <!-- Here begin Sidebar -->
        <div class="col-md-4">

            <div class="widget-main">
                <div class="widget-main-title">
                    <h4 class="widget-title">Thể loại</h4>
                </div>
                <div class="widget-inner">
                    <div class="blog-categories">
                        <div class="row">
                            <ul class="col-md-12">
                                @foreach (var item in @list)
                                {
                                    <li>@Html.ActionLink(Html.Raw(item.Name).ToString(), "Index", new { id = item.Id })</li>
                                }
                            </ul>
                        </div>
                    </div>
                </div> <!-- /.widget-inner -->
            </div> <!-- /.widget-main -->

        </div> <!-- /.col-md-4 -->
    </div>
</div>

ToanThangEdu/ToanThangEdu/Views/UserDocumentItems/Index.cshtml
@model PagedList.IPagedList<ToanThangEdu.Models.DocumentItem>
@using PagedList.Mvc;
@using ToanThangEdu.Models
@using ToanThangEdu.Areas.Admin.Controllers
@{
    //ViewBag.Title = "Tài Liệu - Trung tâm Toàn Thắng";
    //var list = (List<DocumentsCategory>)ViewData["item"];
    ToanThangEducationDBEntities db = new ToanThangEducationDBEntities();
    var listMenu = new List<MenuInView>();
    var listRootId = new List<Int64>();
    foreach (var item in db.DocumentsCategories.OrderBy(x => x.Id))
    {
        if (item.RootId == 0 || item.RootId == null)
        {
            var tmp = Convert.ToInt64(item.Id);
            listRootId.Add(tmp);
        }
    }
    foreach (var item in listRootId)
    {
        MenuInView tmp = new MenuInView();
        tmp.Id = item;
        var listTmp = db.DocumentsCategories.Where(x => x.RootId == item).ToList();
        var rootName = db.DocumentsCategories.Where(x => x.Id == item).FirstOrDefault();
        if (rootName == null)
        {
            tmp.PaMenu = "Root đã được xóa";
        }
        else
        {
            tmp.PaMenu = rootName.Name;
        }

        List<MenuChild> listChild = new List<MenuChild>();
        foreach (var itemChild in listTmp)
        {
            MenuChild menuTmp = new MenuChild();
            var dcTmp = db.DocumentsCategories.Where(x => x.Id == itemChild.Id).FirstOrDefault();
            menuTmp.Id = dcTmp.Id;
            menuTmp.ChiMenu = dcTmp.Name;
            listChild.Add(menuTmp);
        }
        tmp.ChiMenu = listChild;
        listMenu.Add(tmp);
    }
    Layout = "~/Views/Shared/_ToanThangLayout.cshtml";
}

<div class="container">
    <div class="page-title clearfix">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center page-active "><h2><b>TÀI LIỆU CHIA SẺ</b></h2></div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <!-- Here begin Main Content -->
        <div class="col-md-9">
            <div class="row">

                @foreach (var item in Model)
                {
                    <div class="col-md-6">
                        <div class="list-event-item">
                            <div class="box-content-inner clearfix">
                                <div class="list-event-thumb" style="height: 50%">
                                    <a href="@Url.Action("Details", new { id = item.Id })">
                                        @if (item.DocumentURL.Contains(".pdf"))
                                        {
                                            <img src="~/images/Document/pdf.png" alt="No Image" />
                                        }
                                        else
                                        {
                                            <img src="~/images/Document/word.png" alt="No Image" />
                                        }
                                    </a>
                                </div>
                                <div class="list-event-header">
                                    <span class="event-place small-text"><i class="fa fa-globe"></i>@Html.DisplayFor(model => item.DocumentsCategory.Name)</span>

                                </div>
                                <h3 class="event-title">@Html.ActionLink(Html.Raw(item.Name).ToString(), "Details", new { id = item.Id })</h3>
                                @Html.ActionLink("Xem chi tiết", "Details", new { id = item.Id }, htmlAttributes: new { @class = "lightBtn" })

                            </div> <!-- /.box-content-inner -->
                        </div> <!-- /.list-event-item -->

                    </div> <!-- /.col-md-12 -->
                }
            </div> <!-- /.row -->
            @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div> <!-- /.col-md-8 -->
        <!-- Here begin Sidebar -->
        <div class="col-md-3">
            <div class="widget-main">
                <div class="widget-main-title">
                    <h4 class="widget-title">Thể loại</h4>
                </div>
                <div class="widget-inner">
                    <div class="blog-categories">
                        <div class="row">

                            <div>
                                <ul class="nav nav-list sf-menu">
                                    @{
                                        foreach (var item in listMenu)
                                        {
                                            <li style="list-style-type:circle">
                                                <label>
                                                    <a href="@Url.Action("Index","UserDocumentItems",new { id = item.Id})">@item.PaMenu</a>
                                                </label>
                                                @if (item.ChiMenu.Count() >= 1)
                                                {
                                                    <ul>
                                                        @foreach (var itemChild in item.ChiMenu)
                                                        {
                                                            <li>
                                                                <label>
                                                                    <a href="@Url.Action("Index","UserDocumentItems",new { id = itemChild.Id})">@itemChild.ChiMenu</a>
                                                                </label>
                                                            </li>
                                                        }
                                                    </ul>
                                                }

                                            </li>
                                        }
                                    }
                                </ul>

                            </div>
                        </div>
                    </div>
                </div> <!-- /.widget-inner -->
            </div> <!-- /.widget-main -->
            @*<div class="widget-main">
                    <div class="widget-main-title">
                        <h4 class="widget-title">Our Gallery</h4>
                    </div>
                    <div class="widget-inner">
                        <div class="gallery-small-thumbs clearfix">
                            <div class="thumb-small-gallery">
                                <a class="fancybox" rel="gallery1" href="./images/gallery/gallery1.jpg" title="Gallery Tittle One">
                                    <img src="./images/gallery/gallery-small-thumb1.jpg" alt="" />
                                </a>
                            </div>
                            <div class="thumb-small-gallery">
                                <a class="fancybox" rel="gallery1" href="./images/gallery/gallery2.jpg" title="Gallery Tittle One">
                                    <img src="./images/gallery/gallery-small-thumb2.jpg" alt="" />
                                </a>
                            </div>
                            <div class="thumb-small-gallery">
                                <a class="fancybox" rel="gallery1" href="./images/gallery/gallery3.jpg" title="Gallery Tittle One">
                                    <img src="./images/gallery/gallery-small-thumb3.jpg" alt="" />
                                </a>
                            </div>
                            <div class="thumb-small-gallery">
                                <a class="fancybox" rel="gallery1" href="./images/gallery/gallery4.jpg" title="Gallery Tittle One">
                                    <img src="./images/gallery/gallery-small-thumb4.jpg" alt="" />
                                </a>
                            </div>
                            <div class="thumb-small-gallery">
                                <a class="fancybox" rel="gallery1" href="./images/gallery/gallery5.jpg" title="Gallery Tittle One">
                                    <img src="./images/gallery/gallery-small-thumb5.jpg" alt="" />
                                </a>
                            </div>
                            <div class="thumb-small-gallery">
                                <a class="fancybox" rel="gallery1" href="./images/gallery/gallery6.jpg" title="Gallery Tittle One">
                                    <img src="./images/gallery/gallery-small-thumb6.jpg" alt="" />
                                </a>
                            </div>
                            <div class="thumb-small-gallery">
                                <a class="fancybox" rel="gallery1" href="./images/gallery/gallery7.jpg" title="Gallery Tittle One">
                                    <img src="./images/gallery/gallery-small-thumb7.jpg" alt="" />
                                </a>
                            </div>
                            <div class="thumb-small-gallery">
                                <a class="fancybox" rel="gallery1" href="./images/gallery/gallery8.jpg" title="Gallery Tittle One">
                                    <img src="./images/gallery/gallery-small-thumb8.jpg" alt="" />
                                </a>
                            </div>
                        </div> <!-- /.galler-small-thumbs -->
                    </div> <!-- /.widget-inner -->
                </div>*@ <!-- /.widget-main -->
        </div> <!-- /.col-md-4 -->

    </div> <!-- /.row -->
</div> <!-- /.container -->